---
# This playbook contains plays that will install and configure php7-fpm.

- name: install php7-fpm and php7-cli
  apt: pkg={{ item }} state=latest
  with_items:
    - php7-fpm
    - php7-cli

- name: install php7-* extensions
  apt: pkg={{ item }} state=latest
  with_items:
    - php7-common
    - php7-mysql
    - php7-suhosin
    - php7-gd
    - php7-cgi
    - php-pear
    - php7-mcrypt
    - php7-curl
    - php7-intl
    - php7-memcache
    - php7-pgsql
    - php7-sqlite
    - php7-xdebug
    - php7-xmlrpc
    - php-apc

- name: setup default site
  template: src=www.conf dest=/etc/php7/fpm/pool.d/www.conf owner=root group=root mode=0644

- name: copy over php.ini settings file 
  copy: src=php.development.ini dest=/etc/php7/fpm/php.ini
  notify: restart php7-fpm
  

- name: configure php7-fpm extensions (copy custom configuration)
  copy: src={{ item }} dest=/etc/php7/fpm/conf.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - apc.ini
    - memcache.ini
    - xdebug.ini
    - suhosin.ini
  notify: restart php7-fpm
